# Generated by Django 3.1.7 on 2021-09-19 12:53

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='内容'),
        ),
    ]
